<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <!--CVE-2026-40372 https://github.com/advisories/GHSA-9mv3-2cwr-p262-->
    <PackageReference Include="Microsoft.AspNetCore.DataProtection" Version="10.*" />
    <PackageReference Include="Microsoft.Graph" Version="5.*" />
    <PackageReference Include="Microsoft.Identity.Web" Version="4.*" />
    <!--CVE-2026-44503 https://github.com/advisories/GHSA-7j59-v9qr-6fq9-->
    <PackageReference Include="Microsoft.Kiota.Abstractions" Version="2.*" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.*" />
  </ItemGroup>
</Project>
